### ISSUE TITLE
get_domains_using_as_ns not work

### ISSUE THREAD

**Issue by sadshade** [zeropwn/spyse.py#5]
$ spyse -apikey APIKEY --domains-using-as-ns -target ns.example.com -page 1 -param domain

	  ██████  ██▓███ ▓██   ██▓  ██████ ▓█████ 
	▒██    ▒ ▓██░  ██▒▒██  ██▒▒██    ▒ ▓█   ▀ 
	░ ▓██▄   ▓██░ ██▓▒ ▒██ ██░░ ▓██▄   ▒███   
	  ▒   ██▒▒██▄█▓▒ ▒ ░ ▐██▓░  ▒   ██▒▒▓█  ▄ 
	▒██████▒▒▒██▒ ░  ░ ░ ██▒▓░▒██████▒▒░▒████▒
	▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░  ██▒▒▒ ▒ ▒▓▒ ▒ ░░░ ▒░ ░
	░ ░▒  ░ ░░▒ ░     ▓██ ░▒░ ░ ░▒  ░ ░ ░ ░  ░
	░  ░  ░  ░░       ▒ ▒ ░░  ░  ░  ░     ░   
	      ░           ░ ░           ░     ░  ░
	                  ░ ░           by @zer0pwn          
	
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/spyse", line 416, in <module>
    print(get_domains_using_as_ns(args.target, param, page))
  File "/home/ec2-user/.local/bin/spyse", line 211, in get_domains_using_as_ns
    record['ip']['ip']
TypeError: list indices must be integers or slices, not str

**Comment by sadshade** [comment]
It's for target "casper.besserwisser.org"
