### ISSUE TITLE
pkg_resources.ResolutionError: Script 'scripts/spyse' not found in metadata

### ISSUE THREAD

**Issue by ddervosj** [zeropwn/spyse.py#6]
Hello,

After fresh ubuntu install I am unable to get the spyse working.

Git cloned the package and ran pip3 install spyse.py. Once tried to run via spyse -h getting below:

spyse -h
Traceback (most recent call last):
  File "/usr/local/bin/spyse", line 4, in <module>
    __import__('pkg_resources').run_script('spyse.py==0.13.3.9', 'spyse')
  File "/home/xxx/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/xxx/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/spyse' not found in metadata at '/home/xxx/.local/lib/python3.6/site-packages/spyse.py-0.13.3.9.dist-info'

Any idea what may be causing this?

Thanks in advance!

**Comment by ddervosj** [comment]
self-resolved.
