### ISSUE TITLE
Help with spyse.py - can't find '__main__' module in 'spyse' - json - simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by 015H1** [zeropwn/spyse.py#8]
Hello :)

I did...(python3.8, pip3)
>>> git clone https://github.com/zeropwn/spyse.py.git
>>> cd spyse.py 
>>> python3 setup.py install

**Executing this in current path:** >>> python3 spyse -target hackerone.com --subdomains
/root/tools/SPYSE/bin/python3: can't find '__main__' module in 'spyse'

**Command Without python** >>> spyse -target hackerone.com --subdomains
Traceback (most recent call last):
  File "/root/tools/SPYSE/bin/spyse", line 4, in <module>
    __import__('pkg_resources').run_script('spyse.py==0.13.3.9', 'spyse')
  File "/root/tools/SPYSE/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/tools/SPYSE/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/spyse' not found in metadata at '/root/tools/SPYSE/lib/python3.7/site-packages/spyse.py-0.13.3.9.dist-info'

**Executing in /bin/spyse:** >>> python spyse -target hackerone.com --subdomains
Traceback (most recent call last):
  File "spyse", line 410, in <module>
    print(get_subdomains_aggregate(args.target, param, page, raw=args.raw))
  File "spyse", line 266, in get_subdomains_aggregate
    data = s.subdomains_aggregate(target, param=param, page=page)['cidr']
  File "/usr/local/lib/python3.8/dist-packages/spyse.py-0.13.3.9-py3.8.egg/spyse/spyse.py", line 561, in subdomains_aggregate
  File "/usr/lib/python3/dist-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**May you help me, please? Any idea what may be causing this?
Thanks in advance!! Cheers!**

**Comment by rocbr** [comment]
The same

**Comment by BeardOps** [comment]
Having this exact same issue.

**Comment by jonz-secops** [comment]
same issue, not sure where to start on fixing it locally, the error message isn't too helpful to me

**Comment by dddddd2323** [comment]
same issue
