### ISSUE TITLE
Traceback shows JSONDecodeError in Archlinux. (CLOSED, DUPLICATED)

### ISSUE THREAD

**Issue by saltasatelites** [zeropwn/spyse.py#9]
Hi:
I have installed the program directly from Github with a specific dependence for Arch Linux "Python-argparse".
After install and run "python setup.py install" all goes fine, but when I try to run it, shows this error:

>spyse -target xbox.com --subdomains

> Traceback (most recent call last):
  File "/usr/bin/spyse", line 4, in <module>
    __import__('pkg_resources').run_script('spyse.py==0.13.3.9', 'spyse')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.9/site-packages/spyse.py-0.13.3.9-py3.9.egg/EGG-INFO/scripts/spyse", line 410, in <module>
  File "/usr/lib/python3.9/site-packages/spyse.py-0.13.3.9-py3.9.egg/EGG-INFO/scripts/spyse", line 266, in get_subdomains_aggregate
  File "/usr/lib/python3.9/site-packages/spyse.py-0.13.3.9-py3.9.egg/spyse/spyse.py", line 561, in subdomains_aggregate
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Reading the last line, something is wrong with JSONDecode but I have no idea about what's happening.
Any help will be welcome.
Thanks

**Comment by saltasatelites** [comment]
Duplicated. Sorry
